general {
  lock_cmd = hyprlock
}

listener {
  timeout = 120                                 # 2min
  on-timeout = 1password --lock                # lock 1password
}

listener {
    timeout = 330                                 # 5.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'        # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'          # screen on when resume
}

listener {
  timeout = 300                                 # 5min
  on-timeout = loginctl lock-session
}
