preload = /home/kelly/Pictures/Wallpaper/2.jpg
wallpaper = DP-1, /home/kelly/Pictures/Wallpaper/2.jpg
wallpaper = DP-2, /home/kelly/Pictures/Wallpaper/2.jpg
wallpaper = DP-3, /home/kelly/Pictures/Wallpaper/2.jpg
